import { URL } from "./endpoints";

export const BecomeDistributor={
    SeoData:{
        title:'Office Array | Innovative Designs for Enhanced Creativity and Productivity',
        description:"Office Array offers a diverse selection of furniture designed to enhance any workspace. From ergonomic chairs that prioritize comfort and support, to stylish desks built for productivity, each piece combines functionality with aesthetic appeal.",
        keywords:"office chairs, Mesh chair, Desk, Lethrette chair, lather chair",
        canonicalUrl:URL+'/become-distributor',
        url:URL+'/become-distributor',
        
    },
optionsStates:[
  {label:"Andhra Pradesh", value:"AP"},
  {label:"Arunachal Pradesh", value:"AR"},
  {label:"Assam", value:"AS"},
  {label:"Bihar", value:"BR"},
  {label:"Chhattisgarh", value:"CG"},
  {label:"Goa", value:"GA"},
  {label:"Gujarat", value:"GJ"},
  {label:"Haryana", value:"HR"},
  {label:"Himachal Pradesh", value:"HP"},
  {label:"Jammu and Kashmir", value:"JK"},
  {label:"Jharkhand", value:"JH"},
  {label:"Karnataka", value:"KA"},
  {label:"Kerala", value:"KL"},
  {label:"Madhya Pradesh", value:"MP"},
  {label:"Maharashtra", value:"MH"},
  {label:"Manipur", value:"MN"},
  {label:"Meghalaya", value:"ML"},
  {label:"Mizoram", value:"MZ"},
  {label:"Nagaland", value:"NL"},
  {label:"Odisha", value:"OD"},
  {label:"Punjab", value:"PB"},
  {label:"Rajasthan", value:"RJ"},
  {label:"Sikkim", value:"SK"},
  {label:"Tamil Nadu", value:"TN"},
  {label:"Telangana", value:"TS"},
  {label:"Tripura", value:"TR"},
  {label:"Uttarakhand", value:"UK"},
  {label:"Uttar Pradesh", value:"UP"},
  {label:"West Bengal", value:"WB"},
  {label:"Andaman and Nicobar Islands", value:"AN"},
  {label:"Dadra and Nagar Haveli", value:"DN"},
  {label:"Daman and Diu", value:"DD"},
  {label:"Delhi", value:"DL"},
  {label:"Lakshadweep", value:"LD"},
  {label:"Puducherry", value:"PY"}
],
optionsCities:{
AP: [
    { value: 'visakhapatnam', label: 'Visakhapatnam' },
    { value: 'vijayawada', label: 'Vijayawada' },
    { value: 'guntur', label: 'Guntur' },
    { value: 'nellore', label: 'Nellore' },
    { value: 'kurnool', label: 'Kurnool' },
    { value: 'rajahmundry', label: 'Rajahmundry' },
    { value: 'tirupati', label: 'Tirupati' },
    { value: 'kakinada', label: 'Kakinada' },
    { value: 'anantapur', label: 'Anantapur' },
    { value: 'kadapa', label: 'Kadapa' },
    { value: 'ongole', label: 'Ongole' },
    { value: 'eluru', label: 'Eluru' },
    { value: 'machilipatnam', label: 'Machilipatnam' },
    { value: 'chittoor', label: 'Chittoor' },
    { value: 'srikakulam', label: 'Srikakulam' },
    { value: 'vizianagaram', label: 'Vizianagaram' },
    { value: 'tenali', label: 'Tenali' },
    { value: 'proddatur', label: 'Proddatur' },
    { value: 'hindupur', label: 'Hindupur' },
    { value: 'bhimavaram', label: 'Bhimavaram' },
    { value: 'madanapalle', label: 'Madanapalle' },
    { value: 'nandyal', label: 'Nandyal' },
    { value: 'adoni', label: 'Adoni' },
    { value: 'tadepalligudem', label: 'Tadepalligudem' },
    { value: 'tadipatri', label: 'Tadipatri' },
    { value: 'sattenapalle', label: 'Sattenapalle' },
    { value: 'markapur', label: 'Markapur' },
    { value: 'bapatla', label: 'Bapatla' },
    { value: 'narasaraopet', label: 'Narasaraopet' },
    { value: 'chilakaluripet', label: 'Chilakaluripet' },
    { value: 'puttur', label: 'Puttur' },
    { value: 'samalkot', label: 'Samalkot' },
    { value: 'gudur', label: 'Gudur' },
    { value: 'nandigama', label: 'Nandigama' },
    { value: 'ponnur', label: 'Ponnur' },
    { value: 'vinukonda', label: 'Vinukonda' },
    { value: 'mangalagiri', label: 'Mangalagiri' },
    { value: 'palakollu', label: 'Palakollu' },
    { value: 'rayachoti', label: 'Rayachoti' },
    { value: 'pulivendula', label: 'Pulivendula' },
    { value: 'guntakal', label: 'Guntakal' },
    { value: 'dharmavaram', label: 'Dharmavaram' },
    { value: 'tuni', label: 'Tuni' },
    { value: 'mandapeta', label: 'Mandapeta' },
    { value: 'tanuku', label: 'Tanuku' },
    { value: 'narasapuram', label: 'Narasapuram' },
    { value: 'kavali', label: 'Kavali' },
    { value: 'atmakur', label: 'Atmakur' },
    { value: 'jaggayyapeta', label: 'Jaggayyapeta' },
    { value: 'tiruvuru', label: 'Tiruvuru' },
],      
AR: [
    { value: 'itanagar', label: 'Itanagar' },
    { value: 'naharlagun', label: 'Naharlagun' },
    { value: 'pasighat', label: 'Pasighat' },
    { value: 'tezpur', label: 'Tezpur' },
    { value: 'tawang', label: 'Tawang' },
    { value: 'ziro', label: 'Ziro' },
    { value: 'bomdila', label: 'Bomdila' },
    { value: 'roing', label: 'Roing' },
    { value: 'along', label: 'Along' },
    { value: 'khonsa', label: 'Khonsa' },
    { value: 'changlang', label: 'Changlang' },
    { value: 'deomali', label: 'Deomali' },
    { value: 'nirjuli', label: 'Nirjuli' },
    { value: 'seppa', label: 'Seppa' },
    { value: 'daporijo', label: 'Daporijo' },
    { value: 'yupia', label: 'Yupia' },
    { value: 'anini', label: 'Anini' },
    { value: 'koloriang', label: 'Koloriang' },
    { value: 'longding', label: 'Longding' },
    { value: 'likabali', label: 'Likabali' },
    { value: 'mechuka', label: 'Mechuka' },
    { value: 'patkai', label: 'Patkai' },
    { value: 'pangin', label: 'Pangin' },
    { value: 'ruksin', label: 'Ruksin' },
    { value: 'palin', label: 'Palin' },
    { value: 'nampong', label: 'Nampong' },
    { value: 'miao', label: 'Miao' },
    { value: 'jairampur', label: 'Jairampur' },
    { value: 'sagalee', label: 'Sagalee' },
    { value: 'menchukha', label: 'Menchukha' },
    { value: 'kalaktang', label: 'Kalaktang' },
    { value: 'dirang', label: 'Dirang' },
    { value: 'kamba', label: 'Kamba' },
    { value: 'yinkiong', label: 'Yinkiong' },
    { value: 'chaglagam', label: 'Chaglagam' },
    { value: 'hayuliang', label: 'Hayuliang' },
    { value: 'hawai', label: 'Hawai' },
    { value: 'manmao', label: 'Manmao' },
    { value: 'margherita', label: 'Margherita' },
    { value: 'namsai', label: 'Namsai' },
    { value: 'pangin', label: 'Pangin' },
    { value: 'sile', label: 'Sile' },
    { value: 'vijoynagar', label: 'Vijoynagar' },
    { value: 'walong', label: 'Walong' },
    { value: 'yazali', label: 'Yazali' },
    { value: 'zido', label: 'Zido' },
  ],  
AS: [
    { value: 'guwahati', label: 'Guwahati' },
    { value: 'silchar', label: 'Silchar' },
    { value: 'dibrugarh', label: 'Dibrugarh' },
    { value: 'jorhat', label: 'Jorhat' },
    { value: 'nagaon', label: 'Nagaon' },
    { value: 'tinsukia', label: 'Tinsukia' },
    { value: 'tezpur', label: 'Tezpur' },
    { value: 'bongaigaon', label: 'Bongaigaon' },
    { value: 'karimganj', label: 'Karimganj' },
    { value: 'lakhimpur', label: 'Lakhimpur' },
    { value: 'sibsagar', label: 'Sibsagar' },
    { value: 'goalpara', label: 'Goalpara' },
    { value: 'barpeta', label: 'Barpeta' },
    { value: 'dhubri', label: 'Dhubri' },
    { value: 'dhekiajuli', label: 'Dhekiajuli' },
    { value: 'hamren', label: 'Hamren' },
    { value: 'diphu', label: 'Diphu' },
    { value: 'haflong', label: 'Haflong' },
    { value: 'north_lakhimpur', label: 'North Lakhimpur' },
    { value: 'nalbari', label: 'Nalbari' },
    { value: 'bongaigaon', label: 'Bongaigaon' },
    { value: 'morigaon', label: 'Morigaon' },
    { value: 'digboi', label: 'Digboi' },
    { value: 'margherita', label: 'Margherita' },
    { value: 'bilasipara', label: 'Bilasipara' },
    { value: 'udalguri', label: 'Udalguri' },
    { value: 'sarthebari', label: 'Sarthebari' },
    { value: 'rangia', label: 'Rangia' },
    { value: 'hajo', label: 'Hajo' },
    { value: 'howly', label: 'Howly' },
    { value: 'baksa', label: 'Baksa' },
    { value: 'baihata_chariali', label: 'Baihata Chariali' },
    { value: 'bijni', label: 'Bijni' },
    { value: 'boko', label: 'Boko' },
    { value: 'barama', label: 'Barama' },
    { value: 'barpeta_road', label: 'Barpeta Road' },
    { value: 'dhakuakhana', label: 'Dhakuakhana' },
    { value: 'gohpur', label: 'Gohpur' },
    { value: 'hajo', label: 'Hajo' },
    { value: 'hamren', label: 'Hamren' },
    { value: 'jaigaon', label: 'Jaigaon' },
    { value: 'jorabat', label: 'Jorabat' },
    { value: 'kalaigaon', label: 'Kalaigaon' },
    { value: 'karimganj', label: 'Karimganj' },
    { value: 'kokrajhar', label: 'Kokrajhar' },
    { value: 'laokhowa', label: 'Laokhowa' },
    { value: 'lumding', label: 'Lumding' },
    { value: 'mariani', label: 'Mariani' },
    { value: 'naharkatia', label: 'Naharkatia' },
    { value: 'pathsala', label: 'Pathsala' },
    { value: 'rangapara', label: 'Rangapara' },
    { value: 'sarupathar', label: 'Sarupathar' },
    { value: 'tihu', label: 'Tihu' },
    { value: 'titabor', label: 'Titabor' }
],
BR: [
    { value: 'patna', label: 'Patna' },
    { value: 'gaya', label: 'Gaya' },
    { value: 'bhagalpur', label: 'Bhagalpur' },
    { value: 'muzaffarpur', label: 'Muzaffarpur' },
    { value: 'purnia', label: 'Purnia' },
    { value: 'darbhanga', label: 'Darbhanga' },
    { value: 'bihar_sharif', label: 'Bihar Sharif' },
    { value: 'arrah', label: 'Arrah' },
    { value: 'begusarai', label: 'Begusarai' },
    { value: 'katihar', label: 'Katihar' },
    { value: 'munger', label: 'Munger' },
    { value: 'chhapra', label: 'Chhapra' },
    { value: 'danapur', label: 'Danapur' },
    { value: 'saharsa', label: 'Saharsa' },
    { value: 'hajipur', label: 'Hajipur' },
    { value: 'dehri', label: 'Dehri' },
    { value: 'siwan', label: 'Siwan' },
    { value: 'motihari', label: 'Motihari' },
    { value: 'nawada', label: 'Nawada' },
    { value: 'aurangabad', label: 'Aurangabad' },
    { value: 'lakhisarai', label: 'Lakhisarai' },
    { value: 'buxar', label: 'Buxar' },
    { value: 'araria', label: 'Araria' },
    { value: 'jehanabad', label: 'Jehanabad' },
    { value: 'sitamarhi', label: 'Sitamarhi' },
    { value: 'raxaul', label: 'Raxaul' },
    { value: 'jhajha', label: 'Jhajha' },
    { value: 'supaul', label: 'Supaul' },
    { value: 'samastipur', label: 'Samastipur' },
    { value: 'sasaram', label: 'Sasaram' },
    { value: 'madhubani', label: 'Madhubani' },
    { value: 'masaurhi', label: 'Masaurhi' },
    { value: 'bihariganj', label: 'Bihariganj' },
    { value: 'rohtas', label: 'Rohtas' },
    { value: 'forbesganj', label: 'Forbesganj' },
    { value: 'madhepura', label: 'Madhepura' },
    { value: 'hilsa', label: 'Hilsa' },
    { value: 'shahpur', label: 'Shahpur' },
    { value: 'barauli', label: 'Barauli' },
    { value: 'sheikhpura', label: 'Sheikhpura' },
    { value: 'jamalpur', label: 'Jamalpur' },
    { value: 'sugauli', label: 'Sugauli' },
    { value: 'mohiuddinnagar', label: 'Mohiuddinnagar' },
    { value: 'daudnagar', label: 'Daudnagar' },
    { value: 'rafiganj', label: 'Rafiganj' },
    { value: 'bhojpur', label: 'Bhojpur' },
    { value: 'bhabua', label: 'Bhabua' },
    { value: 'madhaipur', label: 'Madhaipur' },
    { value: 'pupri', label: 'Pupri' },
    { value: 'lalganj', label: 'Lalganj' },
    { value: 'barh', label: 'Barh' },
    { value: 'bakhtiarpur', label: 'Bakhtiarpur' },
    { value: 'phulwari_sharif', label: 'Phulwari Sharif' },
    { value: 'harnaut', label: 'Harnaut' },
    { value: 'patahi', label: 'Patahi' },
    { value: 'chhatapur', label: 'Chhatapur' }
],
CG: [
    { value: 'raipur', label: 'Raipur' },
    { value: 'bilaspur', label: 'Bilaspur' },
    { value: 'bhilai', label: 'Bhilai' },
    { value: 'korba', label: 'Korba' },
    { value: 'raigarh', label: 'Raigarh' },
    { value: 'jagdalpur', label: 'Jagdalpur' },
    { value: 'durg', label: 'Durg' },
    { value: 'rajnandgaon', label: 'Rajnandgaon' },
    { value: 'ambikapur', label: 'Ambikapur' },
    { value: 'dhamtari', label: 'Dhamtari' },
    { value: 'mahasamund', label: 'Mahasamund' },
    { value: 'dalli_rajhara', label: 'Dalli Rajhara' },
    { value: 'naya_raipur', label: 'Naya Raipur' },
    { value: 'chirmiri', label: 'Chirmiri' },
    { value: 'dongargarh', label: 'Dongargarh' },
    { value: 'kondagaon', label: 'Kondagaon' },
    { value: 'manendragarh', label: 'Manendragarh' },
    { value: 'khairagarh', label: 'Khairagarh' },
    { value: 'balod', label: 'Balod' },
    { value: 'bhanupratappur', label: 'Bhanupratappur' },
    { value: 'kanker', label: 'Kanker' },
    { value: 'bijapur', label: 'Bijapur' },
    { value: 'dantewada', label: 'Dantewada' },
    { value: 'sukma', label: 'Sukma' },
    { value: 'narayanpur', label: 'Narayanpur' },
    { value: 'jashpur', label: 'Jashpur' },
    { value: 'balrampur', label: 'Balrampur' },
    { value: 'surajpur', label: 'Surajpur' },
    { value: 'gaurela_pendra_marwahi', label: 'Gaurela Pendra Marwahi' },
    { value: 'mohla_manpur', label: 'Mohla Manpur' },
    { value: 'sarangarh_bilaigarh', label: 'Sarangarh Bilaigarh' },
    { value: 'kharsia', label: 'Kharsia' },
    { value: 'saragaon', label: 'Saragaon' },
    { value: 'baramkela', label: 'Baramkela' },
    { value: 'masturi', label: 'Masturi' },
    { value: 'malkharoda', label: 'Malkharoda' },
    { value: 'akaltara', label: 'Akaltara' },
    { value: 'pamgarh', label: 'Pamgarh' },
    { value: 'baloda', label: 'Baloda' },
    { value: 'nairajpur', label: 'Nairajpur' },
    { value: 'pathalgaon', label: 'Pathalgaon' },
    { value: 'baikunthpur', label: 'Baikunthpur' },
    { value: 'bodla', label: 'Bodla' },
    { value: 'barpali', label: 'Barpali' },
    { value: 'charama', label: 'Charama' },
    { value: 'keskal', label: 'Keskal' },
    { value: 'amarwada', label: 'Amarwada' }
],
GA: [
    { value: 'panaji', label: 'Panaji' },
    { value: 'margao', label: 'Margao' },
    { value: 'vasco_da_gama', label: 'Vasco da Gama' },
    { value: 'mapusa', label: 'Mapusa' },
    { value: 'ponda', label: 'Ponda' },
    { value: 'bicholim', label: 'Bicholim' },
    { value: 'curchorem', label: 'Curchorem' },
    { value: 'cuncolim', label: 'Cuncolim' },
    { value: 'sanquelim', label: 'Sanquelim' },
    { value: 'valpoi', label: 'Valpoi' },
    { value: 'mormugao', label: 'Mormugao' },
    { value: 'old_goa', label: 'Old Goa' },
    { value: 'sanguem', label: 'Sanguem' },
    { value: 'canacona', label: 'Canacona' },
    { value: 'quepem', label: 'Quepem' }
],
GJ: [
    { value: 'ahmedabad', label: 'Ahmedabad' },
    { value: 'surat', label: 'Surat' },
    { value: 'vadodara', label: 'Vadodara' },
    { value: 'rajkot', label: 'Rajkot' },
    { value: 'bhavnagar', label: 'Bhavnagar' },
    { value: 'jamnagar', label: 'Jamnagar' },
    { value: 'junagadh', label: 'Junagadh' },
    { value: 'gandhinagar', label: 'Gandhinagar' },
    { value: 'anand', label: 'Anand' },
    { value: 'navsari', label: 'Navsari' },
    { value: 'bharuch', label: 'Bharuch' },
    { value: 'mehsana', label: 'Mehsana' },
    { value: 'bhuj', label: 'Bhuj' },
    { value: 'valsad', label: 'Valsad' },
    { value: 'porbandar', label: 'Porbandar' },
    { value: 'nadiad', label: 'Nadiad' },
    { value: 'morbi', label: 'Morbi' },
    { value: 'palanpur', label: 'Palanpur' },
    { value: 'godhra', label: 'Godhra' },
    { value: 'veraval', label: 'Veraval' },
    { value: 'patan', label: 'Patan' },
    { value: 'dahod', label: 'Dahod' },
    { value: 'botad', label: 'Botad' },
    { value: 'amreli', label: 'Amreli' },
    { value: 'deesa', label: 'Deesa' },
    { value: 'vyara', label: 'Vyara' },
    { value: 'vapi', label: 'Vapi' },
    { value: 'kalol', label: 'Kalol' },
    { value: 'vijapur', label: 'Vijapur' },
    { value: 'surendranagar', label: 'Surendranagar' },
    { value: 'mangrol', label: 'Mangrol' },
    { value: 'kalavad', label: 'Kalavad' },
    { value: 'dwarka', label: 'Dwarka' },
    { value: 'jamkandorna', label: 'Jamkandorna' },
    { value: 'limdi', label: 'Limdi' },
    { value: 'modasa', label: 'Modasa' },
    { value: 'mandvi', label: 'Mandvi' },
    { value: 'visnagar', label: 'Visnagar' },
    { value: 'dhoraji', label: 'Dhoraji' },
    { value: 'keshod', label: 'Keshod' },
    { value: 'sidhpur', label: 'Sidhpur' },
    { value: 'halol', label: 'Halol' },
    { value: 'idargadh', label: 'Idargadh' },
    { value: 'unja', label: 'Unja' },
    { value: 'kadi', label: 'Kadi' },
    { value: 'sidhpur', label: 'Sidhpur' },
    { value: 'dhrol', label: 'Dhrol' },
    { value: 'chhota_udaipur', label: 'Chhota Udaipur' },
    { value: 'halvad', label: 'Halvad' },
    { value: 'babra', label: 'Babra' },
    { value: 'kapadvanj', label: 'Kapadvanj' },
    { value: 'valsad', label: 'Valsad' }
],
HR:[
    { value: 'chandigarh', label: 'Chandigarh' },
    { value: 'faridabad', label: 'Faridabad' },
    { value: 'gurugram', label: 'Gurugram' },
    { value: 'panipat', label: 'Panipat' },
    { value: 'ambala', label: 'Ambala' },
    { value: 'yamunanagar', label: 'Yamunanagar' },
    { value: 'rohtak', label: 'Rohtak' },
    { value: 'hisar', label: 'Hisar' },
    { value: 'karnal', label: 'Karnal' },
    { value: 'sonipat', label: 'Sonipat' },
    { value: 'panchkula', label: 'Panchkula' },
    { value: 'bhiwani', label: 'Bhiwani' },
    { value: 'sirsa', label: 'Sirsa' },
    { value: 'bahadurgarh', label: 'Bahadurgarh' },
    { value: 'jind', label: 'Jind' },
    { value: 'thanesar', label: 'Thanesar' },
    { value: 'kaithal', label: 'Kaithal' },
    { value: 'rewari', label: 'Rewari' },
    { value: 'palwal', label: 'Palwal' },
    { value: 'narwana', label: 'Narwana' },
    { value: 'mohindergarh', label: 'Mohindergarh' },
    { value: 'tohana', label: 'Tohana' },
    { value: 'nuh', label: 'Nuh' },
    { value: 'charkhi_dadri', label: 'Charkhi Dadri' },
    { value: 'fatehabad', label: 'Fatehabad' },
    { value: 'safidon', label: 'Safidon' },
    { value: 'taraori', label: 'Taraori' },
    { value: 'ganaur', label: 'Ganaur' },
    { value: 'lakhan_majra', label: 'Lakhan Majra' },
    { value: 'jhajjar', label: 'Jhajjar' },
    { value: 'kalka', label: 'Kalka' },
    { value: 'shahbad', label: 'Shahbad' },
    { value: 'raipur_rani', label: 'Raipur Rani' },
    { value: 'ratiya', label: 'Ratiya' },
    { value: 'punhana', label: 'Punhana' },
    { value: 'barwala', label: 'Barwala' },
    { value: 'kanina', label: 'Kanina' },
    { value: 'hansi', label: 'Hansi' },
    { value: 'rania', label: 'Rania' },
    { value: 'narnaund', label: 'Narnaund' },
    { value: 'pundri', label: 'Pundri' },
    { value: 'mahendragarh', label: 'Mahendragarh' },
    { value: 'narwar', label: 'Narwar' },
    { value: 'nangal_chaudhry', label: 'Nangal Chaudhry' },
    { value: 'naraingarh', label: 'Naraingarh' },
    { value: 'raipur_rachna', label: 'Raipur Rachna' },
    { value: 'salhawas', label: 'Salhawas' },
    { value: 'samalkha', label: 'Samalkha' },
    { value: 'sonepat', label: 'Sonepat' },
    { value: 'sohna', label: 'Sohna' },
    { value: 'sampla', label: 'Sampla' },
    { value: 'siwan', label: 'Siwan' }
],
HP:[
    { value: 'shimla', label: 'Shimla' },
    { value: 'dharamshala', label: 'Dharamshala' },
    { value: 'manali', label: 'Manali' },
    { value: 'solan', label: 'Solan' },
    { value: 'mandi', label: 'Mandi' },
    { value: 'hamirpur', label: 'Hamirpur' },
    { value: 'bilaspur', label: 'Bilaspur' },
    { value: 'nahan', label: 'Nahan' },
    { value: 'kullu', label: 'Kullu' },
    { value: 'chamba', label: 'Chamba' },
    { value: 'una', label: 'Una' },
    { value: 'palampur', label: 'Palampur' },
    { value: 'kangra', label: 'Kangra' },
    { value: 'kasauli', label: 'Kasauli' },
    { value: 'paonta_sahib', label: 'Paonta Sahib' },
    { value: 'rewalsar', label: 'Rewalsar' },
    { value: 'sundernagar', label: 'Sundernagar' },
    { value: 'nalagarh', label: 'Nalagarh' },
    { value: 'keylong', label: 'Keylong' },
    { value: 'kalpa', label: 'Kalpa' },
    { value: 'reckong_peo', label: 'Reckong Peo' },
    { value: 'narkanda', label: 'Narkanda' },
    { value: 'jubbal', label: 'Jubbal' },
    { value: 'rohru', label: 'Rohru' },
    { value: 'rampur', label: 'Rampur' },
    { value: 'sarahan', label: 'Sarahan' },
    { value: 'theog', label: 'Theog' },
    { value: 'sirmaur', label: 'Sirmaur' },
    { value: 'tira_suzi', label: 'Tira Suzi' },
    { value: 'jogindernagar', label: 'Jogindernagar' },
    { value: 'dalhousie', label: 'Dalhousie' },
    { value: 'kasol', label: 'Kasol' },
    { value: 'spiti', label: 'Spiti' },
    { value: 'kalpa', label: 'Kalpa' },
    { value: 'naggar', label: 'Naggar' },
    { value: 'tirthan_valley', label: 'Tirthan Valley' },
    { value: 'jibhi', label: 'Jibhi' },
    { value: 'parwanoo', label: 'Parwanoo' },
    { value: 'gagret', label: 'Gagret' },
    { value: 'mehatpur', label: 'Mehatpur' },
    { value: 'baddi', label: 'Baddi' },
    { value: 'shoghi', label: 'Shoghi' },
    { value: 'chail', label: 'Chail' },
    { value: 'hatkoti', label: 'Hatkoti' },
    { value: 'kufri', label: 'Kufri' },
    { value: 'mashobra', label: 'Mashobra' },
    { value: 'salooni', label: 'Salooni' },
    { value: 'sandhole', label: 'Sandhole' }
],
JK:[
    { value: 'srinagar', label: 'Srinagar' },
    { value: 'jammu', label: 'Jammu' },
    { value: 'anantnag', label: 'Anantnag' },
    { value: 'baramulla', label: 'Baramulla' },
    { value: 'sopore', label: 'Sopore' },
    { value: 'udhampur', label: 'Udhampur' },
    { value: 'ganderbal', label: 'Ganderbal' },
    { value: 'kathua', label: 'Kathua' },
    { value: 'punch', label: 'Punch' },
    { value: 'rajouri', label: 'Rajouri' },
    { value: 'bandipora', label: 'Bandipora' },
    { value: 'handwara', label: 'Handwara' },
    { value: 'kulgam', label: 'Kulgam' },
    { value: 'pulwama', label: 'Pulwama' },
    { value: 'shopian', label: 'Shopian' },
    { value: 'budgam', label: 'Budgam' },
    { value: 'reasi', label: 'Reasi' },
    { value: 'samba', label: 'Samba' },
    { value: 'doda', label: 'Doda' },
    { value: 'kishtwar', label: 'Kishtwar' },
    { value: 'ramban', label: 'Ramban' },
    { value: 'udhampur', label: 'Udhampur' },
    { value: 'trikuta_nagar', label: 'Trikuta Nagar' },
    { value: 'mendhar', label: 'Mendhar' },
    { value: 'akhnur', label: 'Akhnur' },
    { value: 'kathua', label: 'Kathua' },
    { value: 'bhaderwah', label: 'Bhaderwah' },
    { value: 'kathua', label: 'Kathua' },
    { value: 'sumbal', label: 'Sumbal' },
    { value: 'awantipora', label: 'Awantipora' },
    { value: 'charari_sharief', label: 'Charari Sharief' },
    { value: 'tral', label: 'Tral' },
    { value: 'machil', label: 'Machil' },
    { value: 'batote', label: 'Batote' },
    { value: 'basohli', label: 'Basohli' },
    { value: 'banihal', label: 'Banihal' },
    { value: 'gurez', label: 'Gurez' },
    { value: 'khrew', label: 'Khrew' },
    { value: 'paloura', label: 'Paloura' },
    { value: 'nagrota', label: 'Nagrota' },
    { value: 'mattan', label: 'Mattan' },
    { value: 'quazigund', label: 'Quazigund' },
    { value: 'aripal', label: 'Aripal' },
    { value: 'sangrama', label: 'Sangrama' },
    { value: 'pattan', label: 'Pattan' },
    { value: 'khan_sahib', label: 'Khan Sahib' },
    { value: 'pahalgam', label: 'Pahalgam' },
    { value: 'gulmarg', label: 'Gulmarg' },
    { value: 'sonamarg', label: 'Sonamarg' },
    { value: 'verinag', label: 'Verinag' },
    { value: 'achabal', label: 'Achabal' },
    { value: 'kokernag', label: 'Kokernag' },
    { value: 'yousmarg', label: 'Yousmarg' },
    { value: 'daksum', label: 'Daksum' }
],
JH:[
    { value: 'ranchi', label: 'Ranchi' },
    { value: 'jamshedpur', label: 'Jamshedpur' },
    { value: 'dhanbad', label: 'Dhanbad' },
    { value: 'bokaro', label: 'Bokaro' },
    { value: 'deoghar', label: 'Deoghar' },
    { value: 'hazaribagh', label: 'Hazaribagh' },
    { value: 'giridih', label: 'Giridih' },
    { value: 'ramgarh', label: 'Ramgarh' },
    { value: 'chatra', label: 'Chatra' },
    { value: 'palamu', label: 'Palamu' },
    { value: 'chaibasa', label: 'Chaibasa' },
    { value: 'dumka', label: 'Dumka' },
    { value: 'godda', label: 'Godda' },
    { value: 'pakur', label: 'Pakur' },
    { value: 'sahebganj', label: 'Sahebganj' },
    { value: 'simdega', label: 'Simdega' },
    { value: 'gumla', label: 'Gumla' },
    { value: 'lohardaga', label: 'Lohardaga' },
    { value: 'latehar', label: 'Latehar' },
    { value: 'garhwa', label: 'Garhwa' },
    { value: 'koderma', label: 'Koderma' },
    { value: 'jamtara', label: 'Jamtara' },
    { value: 'khunti', label: 'Khunti' },
    { value: 'saraikela', label: 'Saraikela' },
    { value: 'gamharia', label: 'Gamharia' },
    { value: 'adityapur', label: 'Adityapur' },
    { value: 'tenughat', label: 'Tenughat' },
    { value: 'mango', label: 'Mango' },
    { value: 'ghatsila', label: 'Ghatsila' },
    { value: 'phusro', label: 'Phusro' },
    { value: 'husainabad', label: 'Husainabad' },
    { value: 'medininagar', label: 'Medininagar' },
    { value: 'gandey', label: 'Gandey' },
    { value: 'chakradharpur', label: 'Chakradharpur' },
    { value: 'chandrapura', label: 'Chandrapura' },
    { value: 'ghatshila', label: 'Ghatshila' },
    { value: 'kiriburu', label: 'Kiriburu' },
    { value: 'chauri', label: 'Chauri' },
    { value: 'tundi', label: 'Tundi' },
    { value: 'rajmahal', label: 'Rajmahal' },
    { value: 'pathardih', label: 'Pathardih' },
    { value: 'topchanchi', label: 'Topchanchi' },
    { value: 'kuru', label: 'Kuru' },
    { value: 'tamar', label: 'Tamar' },
    { value: 'angara', label: 'Angara' },
    { value: 'bharno', label: 'Bharno' },
    { value: 'pakartand', label: 'Pakartand' },
    { value: 'barkatha', label: 'Barkatha' },
    { value: 'katkamsandi', label: 'Katkamsandi' }
],
KA:[
    { value: 'bengaluru', label: 'Bengaluru' },
    { value: 'hubli', label: 'Hubli' },
    { value: 'mysuru', label: 'Mysuru' },
    { value: 'mangaluru', label: 'Mangaluru' },
    { value: 'belagavi', label: 'Belagavi' },
    { value: 'davanagere', label: 'Davanagere' },
    { value: 'ballari', label: 'Ballari' },
    { value: 'vijayapura', label: 'Vijayapura' },
    { value: 'shivamogga', label: 'Shivamogga' },
    { value: 'tumakuru', label: 'Tumakuru' },
    { value: 'udupi', label: 'Udupi' },
    { value: 'kolara', label: 'Kolara' },
    { value: 'hassan', label: 'Hassan' },
    { value: 'bhadravathi', label: 'Bhadravathi' },
    { value: 'mandya', label: 'Mandya' },
    { value: 'chikkamagaluru', label: 'Chikkamagaluru' },
    { value: 'bagalkot', label: 'Bagalkot' },
    { value: 'haveri', label: 'Haveri' },
    { value: 'chitradurga', label: 'Chitradurga' },
    { value: 'gadag', label: 'Gadag' },
    { value: 'chikkaballapura', label: 'Chikkaballapura' },
    { value: 'ranebennur', label: 'Ranebennur' },
    { value: 'ramanagara', label: 'Ramanagara' },
    { value: 'gangavathi', label: 'Gangavathi' },
    { value: 'krishnarajapuram', label: 'Krishnarajapuram' },
    { value: 'sindhnur', label: 'Sindhnur' },
    { value: 'yadgir', label: 'Yadgir' },
    { value: 'hosapete', label: 'Hosapete' },
    { value: 'raichur', label: 'Raichur' },
    { value: 'bidar', label: 'Bidar' },
    { value: 'channapatna', label: 'Channapatna' },
    { value: 'kolar', label: 'Kolar' },
    { value: 'kunigal', label: 'Kunigal' },
    { value: 'tirumakudal_narsipur', label: 'Tirumakudal Narsipur' },
    { value: 'kanakapura', label: 'Kanakapura' },
    { value: 'doddaballapur', label: 'Doddaballapur' },
    { value: 'madanapalle', label: 'Madanapalle' },
    { value: 'tarikere', label: 'Tarikere' },
    { value: 'channarayapatna', label: 'Channarayapatna' },
    { value: 'magadi', label: 'Magadi' },
    { value: 'molakalmuru', label: 'Molakalmuru' },
    { value: 'nanjangud', label: 'Nanjangud' },
    { value: 'sidlaghatta', label: 'Sidlaghatta' },
    { value: 'sira', label: 'Sira' },
    { value: 'srirangapatna', label: 'Srirangapatna' },
    { value: 'sulya', label: 'Sulya' },
    { value: 'talikota', label: 'Talikota' },
    { value: 'honnali', label: 'Honnali' },
    { value: 'hunsur', label: 'Hunsur' },
    { value: 'ilkal', label: 'Ilkal' },
    { value: 'indi', label: 'Indi' },
    { value: 'karwar', label: 'Karwar' },
    { value: 'khaniyadhana', label: 'Khaniyadhana' },
    { value: 'malur', label: 'Malur' },
    { value: 'mulbagal', label: 'Mulbagal' },
    { value: 'pandavapura', label: 'Pandavapura' },
    { value: 'pavagada', label: 'Pavagada' },
    { value: 'piriyapatna', label: 'Piriyapatna' },
    { value: 'puttur', label: 'Puttur' },
    { value: 'ron', label: 'Ron' },
    { value: 'sandur', label: 'Sandur' },
    { value: 'sankeshwar', label: 'Sankeshwar' },
    { value: 'shahpur', label: 'Shahpur' },
    { value: 'shiggaon', label: 'Shiggaon' },
    { value: 'shirhatti', label: 'Shirhatti' },
    { value: 'shorapur', label: 'Shorapur' },
    { value: 'sirsi', label: 'Sirsi' },
    { value: 'tekal', label: 'Tekal' },
    { value: 'thirthahalli', label: 'Thirthahalli' },
    { value: 'tikota', label: 'Tikota' },
    { value: 'tiptur', label: 'Tiptur' },
    { value: 'tumkur', label: 'Tumkur' },
    { value: 'yelahanka', label: 'Yelahanka' },
    { value: 'yelandur', label: 'Yelandur' },
    { value: 'yelahanka', label: 'Yelahanka' }
],
KL:[
    { value: 'thiruvananthapuram', label: 'Thiruvananthapuram' },
    { value: 'kochi', label: 'Kochi' },
    { value: 'kozhikode', label: 'Kozhikode' },
    { value: 'thrissur', label: 'Thrissur' },
    { value: 'kollam', label: 'Kollam' },
    { value: 'palakkad', label: 'Palakkad' },
    { value: 'alappuzha', label: 'Alappuzha' },
    { value: 'malappuram', label: 'Malappuram' },
    { value: 'kannur', label: 'Kannur' },
    { value: 'kottayam', label: 'Kottayam' },
    { value: 'kasaragod', label: 'Kasaragod' },
    { value: 'manjeri', label: 'Manjeri' },
    { value: 'thiruvalla', label: 'Thiruvalla' },
    { value: 'payyanur', label: 'Payyanur' },
    { value: 'punalur', label: 'Punalur' },
    { value: 'thalassery', label: 'Thalassery' },
    { value: 'pappinisseri', label: 'Pappinisseri' },
    { value: 'changanassery', label: 'Changanassery' },
    { value: 'kalamassery', label: 'Kalamassery' },
    { value: 'thaliparamba', label: 'Thaliparamba' },
    { value: 'muvattupuzha', label: 'Muvattupuzha' },
    { value: 'neymathai', label: 'Neymathai' },
    { value: 'kayamkulam', label: 'Kayamkulam' },
    { value: 'kanhangad', label: 'Kanhangad' },
    { value: 'tirur', label: 'Tirur' },
    { value: 'kalpetta', label: 'Kalpetta' },
    { value: 'cherthala', label: 'Cherthala' },
    { value: 'kodungallur', label: 'Kodungallur' },
    { value: 'pathanamthitta', label: 'Pathanamthitta' },
    { value: 'chittur', label: 'Chittur' },
    { value: 'attappadi', label: 'Attappadi' },
    { value: 'chengannur', label: 'Chengannur' },
    { value: 'chavakkad', label: 'Chavakkad' },
    { value: 'kasargod', label: 'Kasargod' },
    { value: 'cherthala', label: 'Cherthala' },
    { value: 'irinjalakuda', label: 'Irinjalakuda' },
    { value: 'chavakkad', label: 'Chavakkad' },
    { value: 'chengannur', label: 'Chengannur' },
    { value: 'chittur', label: 'Chittur' },
    { value: 'cherthala', label: 'Cherthala' },
    { value: 'kasargod', label: 'Kasargod' },
    { value: 'cherthala', label: 'Cherthala' },
    { value: 'cherthala', label: 'Cherthala' },
    { value: 'cherthala', label: 'Cherthala' },
    { value: 'cherthala', label: 'Cherthala' },
    { value: 'cherthala', label: 'Cherthala' },
    { value: 'cherthala', label: 'Cherthala' }
],
MP:[
    { value: 'Bhopal', label: 'Bhopal' },
    { value: 'Indore', label: 'Indore' },
    { value: 'Jabalpur', label: 'Jabalpur' },
    { value: 'Gwalior', label: 'Gwalior' },
    { value: 'Ujjain', label: 'Ujjain' },
    { value: 'Sagar', label: 'Sagar' },
    { value: 'Dewas', label: 'Dewas' },
    { value: 'Satna', label: 'Satna' },
    { value: 'Ratlam', label: 'Ratlam' },
    { value: 'Rewa', label: 'Rewa' },
    { value: 'Katni', label: 'Katni' },
    { value: 'Guna', label: 'Guna' },
    { value: 'Hoshangabad', label: 'Hoshangabad' },
    { value: 'Chhindwara', label: 'Chhindwara' },
    { value: 'Damoh', label: 'Damoh' },
    { value: 'Shivpuri', label: 'Shivpuri' },
    { value: 'Vidisha', label: 'Vidisha' },
    { value: 'Burhanpur', label: 'Burhanpur' },
    { value: 'Khandwa', label: 'Khandwa' },
    { value: 'Khargone', label: 'Khargone' },
    { value: 'Neemuch', label: 'Neemuch' },
    { value: 'Morena', label: 'Morena' },
    { value: 'Bhind', label: 'Bhind' },
    { value: 'Shahdol', label: 'Shahdol' },
    { value: 'Chhatarpur', label: 'Chhatarpur' },
    { value: 'Betul', label: 'Betul' },
    { value: 'Sagar', label: 'Sagar' },
    { value: 'Sehore', label: 'Sehore' },
    { value: 'Harda', label: 'Harda' },
    { value: 'Datia', label: 'Datia' },
    { value: 'Mandsaur', label: 'Mandsaur' },
    { value: 'Raisen', label: 'Raisen' },
    { value: 'Seoni', label: 'Seoni' },
    { value: 'Narsimhapur', label: 'Narsimhapur' },
    { value: 'Balaghat', label: 'Balaghat' },
    { value: 'Jhabua', label: 'Jhabua' },
    { value: 'Seoni', label: 'Seoni' },
    { value: 'Hatta', label: 'Hatta' },
    { value: 'Sehore', label: 'Sehore' },
    { value: 'Shivpuri', label: 'Shivpuri' },
    { value: 'Panna', label: 'Panna' },
    { value: 'Barwani', label: 'Barwani' },
    { value: 'Anuppur', label: 'Anuppur' },
    { value: 'Ashoknagar', label: 'Ashoknagar' },
    { value: 'Alirajpur', label: 'Alirajpur' },
    { value: 'Tikamgarh', label: 'Tikamgarh' },
    { value: 'Dindori', label: 'Dindori' },
    { value: 'Sheopur', label: 'Sheopur' },
    { value: 'Singrauli', label: 'Singrauli' },
    { value: 'Agar Malwa', label: 'Agar Malwa' },
    { value: 'Sidhi', label: 'Sidhi' },
    { value: 'Niwari', label: 'Niwari' },
    { value: 'Shajapur', label: 'Shajapur' },
    { value: 'Damoh', label: 'Damoh' },
    { value: 'Neemuch', label: 'Neemuch' },
    { value: 'Dhar', label: 'Dhar' },
    { value: 'Khandwa', label: 'Khandwa' },
    { value: 'Vidisha', label: 'Vidisha' },
    { value: 'Raisen', label: 'Raisen' },
    { value: 'Burhanpur', label: 'Burhanpur' },
    { value: 'Shivpuri', label: 'Shivpuri' },
    { value: 'Mandsaur', label: 'Mandsaur' },
    { value: 'Shivpuri', label: 'Shivpuri' },
    { value: 'Mandsaur', label: 'Mandsaur' }
],
MH:[
        { "value": "mumbai", "label": "Mumbai" },
        { "value": "pune", "label": "Pune" },
        { "value": "nagpur", "label": "Nagpur" },
        { "value": "thane", "label": "Thane" },
        { "value": "nashik", "label": "Nashik" },
        { "value": "aurangabad", "label": "Aurangabad" },
        { "value": "solapur", "label": "Solapur" },
        { "value": "amravati", "label": "Amravati" },
        { "value": "malegaon", "label": "Malegaon" },
        { "value": "kolhapur", "label": "Kolhapur" },
        { "value": "nanded", "label": "Nanded" },
        { "value": "sangli", "label": "Sangli" },
        { "value": "jalgaon", "label": "Jalgaon" },
        { "value": "akola", "label": "Akola" },
        { "value": "latur", "label": "Latur" },
        { "value": "dhule", "label": "Dhule" },
        { "value": "ahmednagar", "label": "Ahmednagar" },
        { "value": "chandrapur", "label": "Chandrapur" },
        { "value": "parbhani", "label": "Parbhani" },
        { "value": "jalna", "label": "Jalna" },
        { "value": "bhusawal", "label": "Bhusawal" },
        { "value": "panvel", "label": "Panvel" },
        { "value": "satara", "label": "Satara" },
        { "value": "beed", "label": "Beed" },
        { "value": "yavatmal", "label": "Yavatmal" },
        { "value": "buldhana", "label": "Buldhana" },
        { "value": "osmanabad", "label": "Osmanabad" },
        { "value": "nandurbar", "label": "Nandurbar" },
        { "value": "washim", "label": "Washim" },
        { "value": "hingoli", "label": "Hingoli" },
        { "value": "gondia", "label": "Gondia" },
        { "value": "raigad", "label": "Raigad" },
        { "value": "wardha", "label": "Wardha" },
        { "value": "buldhana", "label": "Buldana" },
        { "value": "chandrapur", "label": "Chandrapur" },
        { "value": "gadchiroli", "label": "Gadchiroli" },
        { "value": "sindhudurg", "label": "Sindhudurg" },
        { "value": "ratnagiri", "label": "Ratnagiri" },
        { "value": "gadchiroli", "label": "Gadchiroli" },
        { "value": "wardha", "label": "Wardha" },
        { "value": "bhandara", "label": "Bhandara" },
        { "value": "gondia", "label": "Gondia" },
        { "value": "wani", "label": "Wani" },
        { "value": "saoner", "label": "Saoner" },
        { "value": "umred", "label": "Umred" },
        { "value": "daryapur", "label": "Daryapur" },
        { "value": "kinwat", "label": "Kinwat" },
        { "value": "talode", "label": "Talode" },
        { "value": "sakri", "label": "Sakri" },
        { "value": "shirpur", "label": "Shirpur" },
        { "value": "shrigonda", "label": "Shrigonda" },
        { "value": "junnar", "label": "Junnar" }
],
MN: [
        { "value": "imphal", "label": "Imphal" },
        { "value": "thoubal", "label": "Thoubal" },
        { "value": "bishnupur", "label": "Bishnupur" },
        { "value": "churachandpur", "label": "Churachandpur" },
        { "value": "kakching", "label": "Kakching" },
        { "value": "ukhrul", "label": "Ukhrul" },
        { "value": "senapati", "label": "Senapati" },
        { "value": "tamenglong", "label": "Tamenglong" },
        { "value": "jiribam", "label": "Jiribam" },
        { "value": "thoubal", "label": "Thoubal" },
        { "value": "moreh", "label": "Moreh" },
        { "value": "kangpokpi", "label": "Kangpokpi" },
        { "value": "lilong", "label": "Lilong" },
        { "value": "nungba", "label": "Nungba" },
        { "value": "mayang", "label": "Mayang" }
    ],
ML: [
        { "value": "shillong", "label": "Shillong" },
        { "value": "tura", "label": "Tura" },
        { "value": "jowai", "label": "Jowai" },
        { "value": "nongstoin", "label": "Nongstoin" },
        { "value": "nongpoh", "label": "Nongpoh" },
        { "value": "baghmara", "label": "Baghmara" },
        { "value": "williamnagar", "label": "Williamnagar" },
        { "value": "mawkyrwat", "label": "Mawkyrwat" },
        { "value": "resubelpara", "label": "Resubelpara" },
        { "value": "mairang", "label": "Mairang" },
        { "value": "khliehriat", "label": "Khliehriat" },
        { "value": "amarpur", "label": "Amarpur" },
        { "value": "naongkhong", "label": "Naongkhong" },
        { "value": "ranikor", "label": "Ranikor" },
        { "value": "maurang", "label": "Maurang" }
    ],
MZ: [
        { "value": "aizawl", "label": "Aizawl" },
        { "value": "lunglei", "label": "Lunglei" },
        { "value": "champhai", "label": "Champhai" },
        { "value": "saiha", "label": "Saiha" },
        { "value": "kolasib", "label": "Kolasib" },
        { "value": "serchhip", "label": "Serchhip" },
        { "value": "lawngtlai", "label": "Lawngtlai" },
        { "value": "mamit", "label": "Mamit" },
        { "value": "saitual", "label": "Saitual" }
    ],
NL:[
        { "value": "kohima", "label": "Kohima" },
        { "value": "dimapur", "label": "Dimapur" },
        { "value": "mokokchung", "label": "Mokokchung" },
        { "value": "tuensang", "label": "Tuensang" },
        { "value": "wokha", "label": "Wokha" },
        { "value": "zunheboto", "label": "Zunheboto" },
        { "value": "phek", "label": "Phek" },
        { "value": "kohima", "label": "Kohima" },
        { "value": "longleng", "label": "Longleng" },
        { "value": "peren", "label": "Peren" },
        { "value": "mon", "label": "Mon" },
        { "value": "kiphire", "label": "Kiphire" }
    ],
OD:[
        { "value": "bhubaneswar", "label": "Bhubaneswar" },
        { "value": "cuttack", "label": "Cuttack" },
        { "value": "rourkela", "label": "Rourkela" },
        { "value": "berhampur", "label": "Berhampur" },
        { "value": "sambalpur", "label": "Sambalpur" },
        { "value": "puri", "label": "Puri" },
        { "value": "balasore", "label": "Balasore" },
        { "value": "bhadrak", "label": "Bhadrak" },
        { "value": "baripada", "label": "Baripada" },
        { "value": "jagatsinghpur", "label": "Jagatsinghpur" },
        { "value": "jajpur", "label": "Jajpur" },
        { "value": "anugul", "label": "Anugul" },
        { "value": "sundargarh", "label": "Sundargarh" },
        { "value": "kendujhar", "label": "Kendujhar" },
        { "value": "bargarh", "label": "Bargarh" },
        { "value": "dhenkanal", "label": "Dhenkanal" },
        { "value": "jaleswar", "label": "Jaleswar" },
        { "value": "paradeep", "label": "Paradeep" },
        { "value": "boudh", "label": "Boudh" },
        { "value": "sonepur", "label": "Sonepur" },
        { "value": "bhawanipatna", "label": "Bhawanipatna" },
        { "value": "jeypore", "label": "Jeypore" },
        { "value": "kalahandi", "label": "Kalahandi" },
        { "value": "phulbani", "label": "Phulbani" },
        { "value": "rayagada", "label": "Rayagada" },
        { "value": "nuapada", "label": "Nuapada" },
        { "value": "kendrapara", "label": "Kendrapara" },
        { "value": "nabarangpur", "label": "Nabarangpur" },
        { "value": "angul", "label": "Angul" },
        { "value": "cuttack", "label": "Cuttack" },
        { "value": "dhenkanal", "label": "Dhenkanal" },
        { "value": "jagatsinghpur", "label": "Jagatsinghpur" },
        { "value": "nayagarh", "label": "Nayagarh" },
        { "value": "kandhamal", "label": "Kandhamal" },
        { "value": "sambalpur", "label": "Sambalpur" },
        { "value": "debagarh", "label": "Debagarh" },
        { "value": "baleshwar", "label": "Baleshwar" },
        { "value": "khordha", "label": "Khordha" },
        { "value": "malkangiri", "label": "Malkangiri" },
        { "value": "ganjam", "label": "Ganjam" }
    ],
PB:[
        { "value": "amritsar", "label": "Amritsar" },
        { "value": "ludhiana", "label": "Ludhiana" },
        { "value": "jalandhar", "label": "Jalandhar" },
        { "value": "patiala", "label": "Patiala" },
        { "value": "bathinda", "label": "Bathinda" },
        { "value": "hoshiarpur", "label": "Hoshiarpur" },
        { "value": "mohali", "label": "Mohali" },
        { "value": "pathankot", "label": "Pathankot" },
        { "value": "firozpur", "label": "Firozpur" },
        { "value": "batala", "label": "Batala" },
        { "value": "moga", "label": "Moga" },
        { "value": "khanna", "label": "Khanna" },
        { "value": "sangrur", "label": "Sangrur" },
        { "value": "barnala", "label": "Barnala" },
        { "value": "kapurthala", "label": "Kapurthala" },
        { "value": "fazilka", "label": "Fazilka" },
        { "value": "rampura phul", "label": "Rampura Phul" },
        { "value": "phagwara", "label": "Phagwara" },
        { "value": "abohar", "label": "Abohar" },
        { "value": "malerkotla", "label": "Malerkotla" },
        { "value": "gurdaspur", "label": "Gurdaspur" },
        { "value": "mansa", "label": "Mansa" },
        { "value": "nabha", "label": "Nabha" },
        { "value": "jagraon", "label": "Jagraon" },
        { "value": "kharar", "label": "Kharar" },
        { "value": "phillaur", "label": "Phillaur" },
        { "value": "mullanpur dakha", "label": "Mullanpur Dakha" },
        { "value": "samana", "label": "Samana" },
        { "value": "nakodar", "label": "Nakodar" },
        { "value": "sunam", "label": "Sunam" },
        { "value": "barnala", "label": "Barnala" },
        { "value": "sirhind", "label": "Sirhind" },
        { "value": "jandiala guru", "label": "Jandiala Guru" },
        { "value": "nawanshahr", "label": "Nawanshahr" },
        { "value": "dasuya", "label": "Dasuya" },
        { "value": "tarn taran", "label": "Tarn Taran" },
        { "value": "nangal", "label": "Nangal" },
        { "value": "malout", "label": "Malout" },
        { "value": "moonak", "label": "Moonak" },
        { "value": "faridkot", "label": "Faridkot" },
        { "value": "morinda", "label": "Morinda" },
        { "value": "gobindgarh", "label": "Gobindgarh" },
        { "value": "phillaur", "label": "Phillaur" }
    ],
RJ:[
        { "value": "jaipur", "label": "Jaipur" },
        { "value": "jodhpur", "label": "Jodhpur" },
        { "value": "udaipur", "label": "Udaipur" },
        { "value": "kota", "label": "Kota" },
        { "value": "bikaner", "label": "Bikaner" },
        { "value": "ajmer", "label": "Ajmer" },
        { "value": "alwar", "label": "Alwar" },
        { "value": "bhilwara", "label": "Bhilwara" },
        { "value": "sikar", "label": "Sikar" },
        { "value": "barmer", "label": "Barmer" },
        { "value": "jaisalmer", "label": "Jaisalmer" },
        { "value": "chittorgarh", "label": "Chittorgarh" },
        { "value": "bharatpur", "label": "Bharatpur" },
        { "value": "pali", "label": "Pali" },
        { "value": "ganganagar", "label": "Sri Ganganagar" },
        { "value": "sirohi", "label": "Sirohi" },
        { "value": "tonk", "label": "Tonk" },
        { "value": "banswara", "label": "Banswara" },
        { "value": "nagaur", "label": "Nagaur" },
        { "value": "dungarpur", "label": "Dungarpur" },
        { "value": "baran", "label": "Baran" },
        { "value": "jhalawar", "label": "Jhalawar" },
        { "value": "sawai madhopur", "label": "Sawai Madhopur" },
        { "value": "karauli", "label": "Karauli" },
        { "value": "rajsamand", "label": "Rajsamand" },
        { "value": "bundi", "label": "Bundi" },
        { "value": "sikar", "label": "Sikar" },
        { "value": "jalore", "label": "Jalore" },
        { "value": "churu", "label": "Churu" },
        { "value": "jalor", "label": "Jalor" },
        { "value": "banswara", "label": "Banswara" },
        { "value": "bhilwara", "label": "Bhilwara" },
        { "value": "dausa", "label": "Dausa" },
        { "value": "hanumangarh", "label": "Hanumangarh" },
        { "value": "jalore", "label": "Jalore" },
        { "value": "jhalawar", "label": "Jhalawar" },
        { "value": "pali", "label": "Pali" },
        { "value": "rajsamand", "label": "Rajsamand" },
        { "value": "swai madhopur", "label": "Sawai Madhopur" },
        { "value": "tonk", "label": "Tonk" },
        { "value": "gangapur", "label": "Gangapur" },
        { "value": "sirohi", "label": "Sirohi" },
        { "value": "churu", "label": "Churu" },
        { "value": "jaisalmer", "label": "Jaisalmer" },
        { "value": "banswara", "label": "Banswara" }
    ],
SK:[
        { "value": "gangtok", "label": "Gangtok" },
        { "value": "namchi", "label": "Namchi" },
        { "value": "mangan", "label": "Mangan" },
        { "value": "singtam", "label": "Singtam" },
        { "value": "rangpo", "label": "Rangpo" },
        { "value": "gyalshing", "label": "Gyalshing" },
        { "value": "jorethang", "label": "Jorethang" },
        { "value": "melli", "label": "Melli" },
        { "value": "rinchenpong", "label": "Rinchenpong" },
        { "value": "gezing", "label": "Geyzing" },
        { "value": "ranipool", "label": "Ranipool" },
        { "value": "soreng", "label": "Soreng" },
        { "value": "tadong", "label": "Tadong" },
        { "value": "chungthang", "label": "Chungthang" },
        { "value": "martam", "label": "Martam" }
    ],
TN: [
        { "value": "chennai", "label": "Chennai" },
        { "value": "coimbatore", "label": "Coimbatore" },
        { "value": "madurai", "label": "Madurai" },
        { "value": "tiruchirappalli", "label": "Tiruchirappalli" },
        { "value": "salem", "label": "Salem" },
        { "value": "tirunelveli", "label": "Tirunelveli" },
        { "value": "tiruppur", "label": "Tiruppur" },
        { "value": "vellore", "label": "Vellore" },
        { "value": "erode", "label": "Erode" },
        { "value": "thoothukudi", "label": "Thoothukudi" },
        { "value": "nagercoil", "label": "Nagercoil" },
        { "value": "thanjavur", "label": "Thanjavur" },
        { "value": "dindigul", "label": "Dindigul" },
        { "value": "cuddalore", "label": "Cuddalore" },
        { "value": "kanchipuram", "label": "Kanchipuram" },
        { "value": "tiruvannamalai", "label": "Tiruvannamalai" },
        { "value": "kumbakonam", "label": "Kumbakonam" },
        { "value": "karur", "label": "Karur" },
        { "value": "neyveli", "label": "Neyveli" },
        { "value": "hosur", "label": "Hosur" },
        { "value": "nagercoil", "label": "Nagercoil" },
        { "value": "sivakasi", "label": "Sivakasi" },
        { "value": "ooty", "label": "Ooty" },
        { "value": "pollachi", "label": "Pollachi" },
        { "value": "krishnagiri", "label": "Krishnagiri" },
        { "value": "rasipuram", "label": "Rasipuram" },
        { "value": "udumalpet", "label": "Udumalpet" },
        { "value": "vellakovil", "label": "Vellakovil" },
        { "value": "tenkasi", "label": "Tenkasi" },
        { "value": "sankarankovil", "label": "Sankarankovil" },
        { "value": "thiruvarur", "label": "Thiruvarur" },
        { "value": "rajapalayam", "label": "Rajapalayam" },
        { "value": "pudukkottai", "label": "Pudukkottai" },
        { "value": "perambalur", "label": "Perambalur" },
        { "value": "rajapalayam", "label": "Rajapalayam" },
        { "value": "sathyamangalam", "label": "Sathyamangalam" },
        { "value": "namakkal", "label": "Namakkal" },
        { "value": "nagapattinam", "label": "Nagapattinam" },
        { "value": "padmanabhapuram", "label": "Padmanabhapuram" },
        { "value": "aruppukkottai", "label": "Aruppukkottai" },
        { "value": "pattukkottai", "label": "Pattukkottai" },
        { "value": "puvathur", "label": "Puvathur" },
        { "value": "virudhunagar", "label": "Virudhunagar" },
        { "value": "udankudi", "label": "Udankudi" },
        { "value": "mudukulathur", "label": "Mudukulathur" }
    ],
TR: [
        { "value": "agartala", "label": "Agartala" },
        { "value": "udaipur", "label": "Udaipur" },
        { "value": "belonia", "label": "Belonia" },
        { "value": "dharmnagar", "label": "Dharmnagar" },
        { "value": "kailasahar", "label": "Kailasahar" },
        { "value": "kamalpur", "label": "Kamalpur" },
        { "value": "khowai", "label": "Khowai" },
        { "value": "sonamura", "label": "Sonamura" },
        { "value": "ranirbazar", "label": "Ranirbazar" },
        { "value": "sabroom", "label": "Sabroom" },
        { "value": "dharmanagar", "label": "Dharmanagar" },
        { "value": "amarpur", "label": "Amarpur" },
        { "value": "ambassa", "label": "Ambassa" },
        { "value": "jogendranagar", "label": "Jogendranagar" }
    ],
UK: [
        { "value": "dehradun", "label": "Dehradun" },
        { "value": "haridwar", "label": "Haridwar" },
        { "value": "rishikesh", "label": "Rishikesh" },
        { "value": "haldwani", "label": "Haldwani" },
        { "value": "rudrapur", "label": "Rudrapur" },
        { "value": "kashipur", "label": "Kashipur" },
        { "value": "ramnagar", "label": "Ramnagar" },
        { "value": "roorkee", "label": "Roorkee" },
        { "value": "almora", "label": "Almora" },
        { "value": "pithoragarh", "label": "Pithoragarh" },
        { "value": "nainital", "label": "Nainital" },
        { "value": "uttarkashi", "label": "Uttarkashi" },
        { "value": "mussoorie", "label": "Mussoorie" },
        { "value": "tehri", "label": "Tehri" },
        { "value": "chamoli", "label": "Chamoli" },
        { "value": "bageshwar", "label": "Bageshwar" },
        { "value": "champawat", "label": "Champawat" },
        { "value": "dwarahat", "label": "Dwarahat" },
        { "value": "khatima", "label": "Khatima" },
        { "value": "sitarganj", "label": "Sitarganj" },
        { "value": "pauri", "label": "Pauri" },
        { "value": "ranikhet", "label": "Ranikhet" },
        { "value": "jaspur", "label": "Jaspur" },
        { "value": "kashipur", "label": "Kashipur" },
        { "value": "mukteshwar", "label": "Mukteshwar" },
        { "value": "devprayag", "label": "Devprayag" },
        { "value": "gangotri", "label": "Gangotri" },
        { "value": "yamunotri", "label": "Yamunotri" },
        { "value": "badrinath", "label": "Badrinath" },
        { "value": "kedarnath", "label": "Kedarnath" }
    ],
UP: [
    { "value": "agra", "label": "Agra" },
    { "value": "allahabad", "label": "Allahabad" },
    { "value": "aligarh", "label": "Aligarh" },
    { "value": "ambedkar nagar", "label": "Ambedkar Nagar" },
    { "value": "amethi", "label": "Amethi" },
    { "value": "amroha", "label": "Amroha" },
    { "value": "auraiya", "label": "Auraiya" },
    { "value": "azamgarh", "label": "Azamgarh" },
    { "value": "baghpat", "label": "Baghpat" },
    { "value": "bahraich", "label": "Bahraich" },
    { "value": "ballia", "label": "Ballia" },
    { "value": "balrampur", "label": "Balrampur" },
    { "value": "banda", "label": "Banda" },
    { "value": "barabanki", "label": "Barabanki" },
    { "value": "bareilly", "label": "Bareilly" },
    { "value": "basti", "label": "Basti" },
    { "value": "bhadohi", "label": "Bhadohi" },
    { "value": "bijnor", "label": "Bijnor" },
    { "value": "budaun", "label": "Budaun" },
    { "value": "bulandshahr", "label": "Bulandshahr" },
    { "value": "chandauli", "label": "Chandauli" },
    { "value": "chitrakoot", "label": "Chitrakoot" },
    { "value": "deoria", "label": "Deoria" },
    { "value": "etah", "label": "Etah" },
    { "value": "etawah", "label": "Etawah" },
    { "value": "faizabad", "label": "Faizabad" },
    { "value": "farrukhabad", "label": "Farrukhabad" },
    { "value": "fatehpur", "label": "Fatehpur" },
    { "value": "firozabad", "label": "Firozabad" },
    { "value": "gautam buddha nagar", "label": "Gautam Buddha Nagar" },
    { "value": "ghaziabad", "label": "Ghaziabad" },
    { "value": "ghazipur", "label": "Ghazipur" },
    { "value": "gonda", "label": "Gonda" },
    { "value": "gorakhpur", "label": "Gorakhpur" },
    { "value": "hamirpur", "label": "Hamirpur" },
    { "value": "hapur", "label": "Hapur" },
    { "value": "hardoi", "label": "Hardoi" },
    { "value": "hathras", "label": "Hathras" },
    { "value": "jalaun", "label": "Jalaun" },
    { "value": "jaunpur", "label": "Jaunpur" },
    { "value": "jhansi", "label": "Jhansi" },
    { "value": "kannauj", "label": "Kannauj" },
    { "value": "kanpur dehat", "label": "Kanpur Dehat" },
    { "value": "kanpur nagar", "label": "Kanpur Nagar" },
    { "value": "kanshiram nagar", "label": "Kanshiram Nagar" },
    { "value": "kaushambi", "label": "Kaushambi" },
    { "value": "kushinagar", "label": "Kushinagar" },
    { "value": "lakhimpur kheri", "label": "Lakhimpur Kheri" },
    { "value": "lalitpur", "label": "Lalitpur" },
    { "value": "lucknow", "label": "Lucknow" },
    { "value": "maharajganj", "label": "Maharajganj" },
    { "value": "mahoba", "label": "Mahoba" },
    { "value": "mainpuri", "label": "Mainpuri" },
    { "value": "mathura", "label": "Mathura" },
    { "value": "mau", "label": "Mau" },
    { "value": "meerut", "label": "Meerut" },
    { "value": "mirzapur", "label": "Mirzapur" },
    { "value": "moradabad", "label": "Moradabad" },
    { "value": "muzaffarnagar", "label": "Muzaffarnagar" },
    { "value": "pilibhit", "label": "Pilibhit" },
    { "value": "pratapgarh", "label": "Pratapgarh" },
    { "value": "rae bareli", "label": "Rae Bareli" },
    { "value": "rampur", "label": "Rampur" },
    { "value": "saharanpur", "label": "Saharanpur" },
    { "value": "sambhal", "label": "Sambhal" },
    { "value": "sant kabir nagar", "label": "Sant Kabir Nagar" },
    { "value": "shahjahanpur", "label": "Shahjahanpur" },
    { "value": "shamli", "label": "Shamli" },
    { "value": "shravasti", "label": "Shravasti" },
    { "value": "siddharthnagar", "label": "Siddharthnagar" },
    { "value": "sitapur", "label": "Sitapur" },
    { "value": "sonbhadra", "label": "Sonbhadra" },
    { "value": "sultanpur", "label": "Sultanpur" },
    { "value": "unnao", "label": "Unnao" },
    { "value": "varanasi", "label": "Varanasi" }
],
WB: [
    { "value": "kolkata", "label": "Kolkata" },
    { "value": "asansol", "label": "Asansol" },
    { "value": "siliguri", "label": "Siliguri" },
    { "value": "durgapur", "label": "Durgapur" },
    { "value": "bardhaman", "label": "Bardhaman" },
    { "value": "english bazar", "label": "English Bazar" },
    { "value": "baharampur", "label": "Baharampur" },
    { "value": "habra", "label": "Habra" },
    { "value": "krishnanagar", "label": "Krishnanagar" },
    { "value": "jalpaiguri", "label": "Jalpaiguri" },
    { "value": "santipur", "label": "Santipur" },
    { "value": "kharagpur", "label": "Kharagpur" },
    { "value": "shantipur", "label": "Shantipur" },
    { "value": "dankuni", "label": "Dankuni" },
    { "value": "dhulian", "label": "Dhulian" },
    { "value": "medinipur", "label": "Medinipur" },
    { "value": "ranaghat", "label": "Ranaghat" },
    { "value": "haldia", "label": "Haldia" },
    { "value": "raigunj", "label": "Raigunj" },
    { "value": "cooch behar", "label": "Cooch Behar" },
    { "value": "kalyani", "label": "Kalyani" },
    { "value": "malda", "label": "Malda" },
    { "value": "jalpaiguri", "label": "Jalpaiguri" },
    { "value": "alipurduar", "label": "Alipurduar" },
    { "value": "balurghat", "label": "Balurghat" },
    { "value": "bankura", "label": "Bankura" },
    { "value": "darjeeling", "label": "Darjeeling" },
    { "value": "diamond harbour", "label": "Diamond Harbour" },
    { "value": "jhargram", "label": "Jhargram" },
    { "value": "krishnanagar", "label": "Krishnanagar" },
    { "value": "malbazar", "label": "Malbazar" },
    { "value": "rampurhat", "label": "Rampurhat" },
    { "value": "siuri", "label": "Siuri" },
    { "value": "tezpur", "label": "Tezpur" }
],
AN: [
    { "value": "port blair", "label": "Port Blair" },
    { "value": "havelock island", "label": "Havelock Island" },
    { "value": "neil island", "label": "Neil Island" },
    { "value": "diglipur", "label": "Diglipur" },
    { "value": "mayabunder", "label": "Mayabunder" },
    { "value": "rangat", "label": "Rangat" },
    { "value": "ferargunj", "label": "Ferargunj" },
    { "value": "bamboo flat", "label": "Bamboo Flat" },
    { "value": "garacharma", "label": "Garacharma" },
    { "value": "nancowrie", "label": "Nancowrie" },
    { "value": "kamorta", "label": "Kamorta" },
    { "value": "campbell bay", "label": "Campbell Bay" },
    { "value": "car nicobar", "label": "Car Nicobar" },
    { "value": "great nicobar", "label": "Great Nicobar" },
    { "value": "little andaman", "label": "Little Andaman" },
    { "value": "nicobar", "label": "Nicobar" },
    { "value": "north brother island", "label": "North Brother Island" },
    { "value": "south brother island", "label": "South Brother Island" },
    { "value": "teressa", "label": "Teressa" }
],
DN:[
    { "value": "silvassa", "label": "Silvassa" },
    { "value": "dadra", "label": "Dadra" },
    { "value": "nagar haveli", "label": "Nagar Haveli" },
    { "value": "amli", "label": "Amli" },
    { "value": "khanvel", "label": "Khanvel" },
    { "value": "vapi", "label": "Vapi" },
    { "value": "naroli", "label": "Naroli" },
    { "value": "samarvarni", "label": "Samarvarni" },
    { "value": "rakholi", "label": "Rakholi" },
    { "value": "sili", "label": "Sili" },
    { "value": "velugam", "label": "Velugam" }
],
DD:[
    { "value": "daman", "label": "Daman" },
    { "value": "diu", "label": "Diu" },
    { "value": "nani daman", "label": "Nani Daman" },
    { "value": "moti daman", "label": "Moti Daman" },
    { "value": "kadaiya", "label": "Kadaiya" },
    { "value": "devka beach", "label": "Devka Beach" },
    { "value": "jampore beach", "label": "Jampore Beach" },
    { "value": "dabhel", "label": "Dabhel" },
    { "value": "fudam", "label": "Fudam" },
    { "value": "ghoghla", "label": "Ghoghla" },
    { "value": "varkund", "label": "Varkund" }
],
DL:[
    { "value": "connaught place", "label": "Connaught Place" },
    { "value": "karol bagh", "label": "Karol Bagh" },
    { "value": "chandni chowk", "label": "Chandni Chowk" },
    { "value": "lajpat nagar", "label": "Lajpat Nagar" },
    { "value": "saket", "label": "Saket" },
    { "value": "dwarka", "label": "Dwarka" },
    { "value": "rohini", "label": "Rohini" },
    { "value": "punjabi bagh", "label": "Punjabi Bagh" },
    { "value": "vasant kunj", "label": "Vasant Kunj" },
    { "value": "mayur vihar", "label": "Mayur Vihar" },
    { "value": "hauz khas", "label": "Hauz Khas" },
    { "value": "khan market", "label": "Khan Market" },
    { "value": "greater kailash", "label": "Greater Kailash" },
    { "value": "nehru place", "label": "Nehru Place" },
    { "value": "janakpuri", "label": "Janakpuri" },
    { "value": "south extension", "label": "South Extension" },
    { "value": "laxmi nagar", "label": "Laxmi Nagar" },
    { "value": "vivek vihar", "label": "Vivek Vihar" },
    { "value": "shahdara", "label": "Shahdara" },
    { "value": "chhatarpur", "label": "Chhatarpur" },
    { "value": "dwarka sector 23", "label": "Dwarka Sector 23" },
    { "value": "pitampura", "label": "Pitampura" },
    { "value": "rajouri garden", "label": "Rajouri Garden" },
    { "value": "malviya nagar", "label": "Malviya Nagar" },
    { "value": "kapashera", "label": "Kapashera" },
    { "value": "najafgarh", "label": "Najafgarh" },
    { "value": "vijay nagar", "label": "Vijay Nagar" },
    { "value": "paschim vihar", "label": "Paschim Vihar" }
],
LD:[
    { "value": "kavaratti", "label": "Kavaratti" },
    { "value": "agatti", "label": "Agatti" },
    { "value": "minicoy", "label": "Minicoy" },
    { "value": "andrott", "label": "Andrott" },
    { "value": "kalpeni", "label": "Kalpeni" },
    { "value": "amini", "label": "Amini" },
    { "value": "kadmat", "label": "Kadmat" },
    { "value": "chetlat", "label": "Chetlat" },
    { "value": "bitra", "label": "Bitra" },
    { "value": "kiltan", "label": "Kiltan" },
    { "value": "perumal par", "label": "Perumal Par" }
],
PY:[
    { "value": "white town", "label": "White Town" },
    { "value": "beach road", "label": "Beach Road" },
    { "value": "heritage town", "label": "Heritage Town" },
    { "value": "auroville", "label": "Auroville" },
    { "value": "mission street", "label": "Mission Street" },
    { "value": "mg road", "label": "MG Road" },
    { "value": "lawspet", "label": "Lawspet" },
    { "value": "rainbow nagar", "label": "Rainbow Nagar" },
    { "value": "venkata nagar", "label": "Venkata Nagar" },
    { "value": "nellithope", "label": "Nellithope" },
    { "value": "murungapakkam", "label": "Murungapakkam" },
    { "value": "reddiarpalayam", "label": "Reddiarpalayam" },
    { "value": "karuvadikuppam", "label": "Karuvadikuppam" },
    { "value": "nellithope", "label": "Nellithope" },
    { "value": "kamaraj salai", "label": "Kamaraj Salai" },
    { "value": "velrampet", "label": "Velrampet" },
    { "value": "ellaiyamman koil street", "label": "Ellaiyamman Koil Street" },
    { "value": "villianur", "label": "Villianur" },
    { "value": "kalapet", "label": "Kalapet" }
],
}
    
}